from enum import StrEnum


class InvestigationStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    PARTIAL = "PARTIAL"


class ResearchTaskStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ResearchTaskType(StrEnum):
    IDENTIFY_ENTITY = "IDENTIFY_ENTITY"
    WEB_SEARCH = "WEB_SEARCH"
    DOMAIN_LOOKUP = "DOMAIN_LOOKUP"
    PUBLIC_MENTIONS = "PUBLIC_MENTIONS"


class FakeResearchMode(StrEnum):
    SUCCESS = "SUCCESS"
    FAIL_ONCE = "FAIL_ONCE"
    ALWAYS_FAIL = "ALWAYS_FAIL"
    SLOW = "SLOW"
    PIPELINE_SUCCESS = "PIPELINE_SUCCESS"


class EntityType(StrEnum):
    PERSON = "PERSON"
    COMPANY = "COMPANY"
    ORGANIZATION = "ORGANIZATION"
    DOMAIN = "DOMAIN"
    ADDRESS = "ADDRESS"
    DOCUMENT = "DOCUMENT"


class EntityResolutionDecision(StrEnum):
    MATCH_EXISTING = "MATCH_EXISTING"
    CREATE_NEW = "CREATE_NEW"
    POSSIBLE_MATCH = "POSSIBLE_MATCH"


class EntityResolutionCandidateStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    AUTO_MATCHED = "AUTO_MATCHED"


class RelationshipType(StrEnum):
    DIRECTOR_OF = "DIRECTOR_OF"
    OWNER_OF = "OWNER_OF"
    EMPLOYEE_OF = "EMPLOYEE_OF"
    RELATED_TO = "RELATED_TO"
    SHARES_ADDRESS_WITH = "SHARES_ADDRESS_WITH"
    OWNS_DOMAIN = "OWNS_DOMAIN"
    MENTIONED_IN = "MENTIONED_IN"
    SUBSIDIARY_OF = "SUBSIDIARY_OF"
    PARTNER_OF = "PARTNER_OF"


class RelationshipClaimKind(StrEnum):
    AFFIRMS = "AFFIRMS"
    NEGATES = "NEGATES"
    ENDS = "ENDS"


class RelationshipCandidateStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    AUTO_ACCEPTED = "AUTO_ACCEPTED"
    CONTRADICTED = "CONTRADICTED"


class RelationshipDecisionType(StrEnum):
    AUTO_ACCEPT = "AUTO_ACCEPT"
    POSSIBLE = "POSSIBLE"
    REJECT = "REJECT"
    CONTRADICT = "CONTRADICT"


class EvidenceType(StrEnum):
    SUPPORTING = "SUPPORTING"
    CONTRADICTING = "CONTRADICTING"
    TEMPORAL_UPDATE = "TEMPORAL_UPDATE"


class AssertionStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    PROBABLE = "PROBABLE"
    POSSIBLE = "POSSIBLE"
    UNVERIFIED = "UNVERIFIED"
    CONTRADICTED = "CONTRADICTED"


class InvestigationReportType(StrEnum):
    EXECUTIVE_SUMMARY = "EXECUTIVE_SUMMARY"
    CORPORATE_PROFILE = "CORPORATE_PROFILE"
    RELATIONSHIP_SUMMARY = "RELATIONSHIP_SUMMARY"
    TIMELINE_SUMMARY = "TIMELINE_SUMMARY"


class InvestigationReportStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
