from enum import StrEnum


class InvestigationStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    PARTIAL = "PARTIAL"


class ResearchTaskStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class EntityType(StrEnum):
    PERSON = "PERSON"
    COMPANY = "COMPANY"
    ORGANIZATION = "ORGANIZATION"
    DOMAIN = "DOMAIN"
    ADDRESS = "ADDRESS"
    DOCUMENT = "DOCUMENT"


class RelationshipType(StrEnum):
    DIRECTOR_OF = "DIRECTOR_OF"
    OWNER_OF = "OWNER_OF"
    EMPLOYEE_OF = "EMPLOYEE_OF"
    RELATED_TO = "RELATED_TO"
    SHARES_ADDRESS_WITH = "SHARES_ADDRESS_WITH"
    OWNS_DOMAIN = "OWNS_DOMAIN"
    MENTIONED_IN = "MENTIONED_IN"
    SUBSIDIARY_OF = "SUBSIDIARY_OF"
    PARTNER_OF = "PARTNER_OF"


class AssertionStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    PROBABLE = "PROBABLE"
    POSSIBLE = "POSSIBLE"
    UNVERIFIED = "UNVERIFIED"
    CONTRADICTED = "CONTRADICTED"
