import { expect, test } from "@playwright/test";

test("dashboard to grounded report workspace journey",async({page})=>{
  const title=`E2E workspace ${Date.now()}`;
  await page.goto("/");
  await expect(page.getByRole("heading",{name:"Investigations"})).toBeVisible();
  await page.getByRole("main").getByRole("link",{name:/New investigation/}).click();
  await page.getByLabel(/Title/).fill(title);
  await page.getByLabel(/Original query/).fill("Investigate Jane Doe, ACME, its directors, ownership, and relevant domains.");
  await page.getByRole("checkbox",{name:/Start automatically/}).uncheck();
  await page.getByRole("button",{name:/Create investigation/}).click();
  await expect(page.getByRole("heading",{name:title})).toBeVisible();
  await expect(page.getByText("DRAFT",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Start"}).click();
  await expect(page.getByText("COMPLETED",{exact:true})).toBeVisible({timeout:60_000});
  await page.getByLabel("Investigation workspace").getByRole("button",{name:"Tasks",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Research tasks",exact:true})).toBeVisible();
  await expect(page.locator("tbody tr").first()).toBeVisible();
  await page.getByLabel("Investigation workspace").getByRole("button",{name:"Entities"}).click();
  await expect(page.getByRole("heading",{name:"Entities",exact:true})).toBeVisible();
  await expect(page.locator("tbody tr").first()).toBeVisible();
  await page.locator("tbody tr").first().click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByRole("button",{name:"Close detail"}).click();
  await page.getByLabel("Investigation workspace").getByRole("button",{name:"Relationships"}).click();
  await expect(page.getByRole("heading",{name:"Relationships",exact:true})).toBeVisible();
  await expect(page.locator("tbody tr").first()).toBeVisible();
  await page.locator("tbody tr").first().click();
  await expect(page.getByRole("dialog",{name:"Relationship evidence"}).getByRole("heading",{name:"Supporting evidence",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Close detail"}).click();
  await page.getByLabel("Investigation workspace").getByRole("button",{name:"Sources"}).click();
  await expect(page.getByRole("heading",{name:"Sources",exact:true})).toBeVisible();
  await expect(page.locator("tbody tr").first()).toBeVisible();
  await page.getByLabel("Investigation workspace").getByRole("button",{name:"Documents"}).click();
  await expect(page.getByRole("heading",{name:"Documents",exact:true})).toBeVisible();
  await page.locator("tbody tr").first().click();
  await expect(page.getByRole("dialog",{name:"Document detail"})).toBeVisible();
  await expect(page.getByRole("heading",{name:"Plain-text preview"})).toBeVisible();
  await page.getByRole("button",{name:"Close detail"}).click();
  await page.getByLabel("Investigation workspace").getByRole("button",{name:"Timeline",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Timeline",exact:true})).toBeVisible();
  await expect(page.getByRole("heading",{name:"No dated events",exact:true})).toBeVisible();
  await page.getByLabel("Investigation workspace").getByRole("button",{name:"Graph"}).click();
  await expect(page.getByTestId("graph-canvas").locator(".react-flow__node").first()).toBeVisible();
  await page.getByLabel("Investigation workspace").getByRole("button",{name:"Ask",exact:true}).click();
  await page.getByLabel("Question").fill("Dr. Juan Pérez fue designado director de ACME S.A.");
  await page.locator(".ask-form").getByRole("button",{name:"Ask",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Grounded answer"})).toBeVisible();
  await expect(page.getByRole("heading",{name:"Citations"})).toBeVisible();
  await page.getByLabel("Investigation workspace").getByRole("button",{name:"Reports"}).click();
  await page.getByRole("button",{name:/Generate report/}).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await expect(page.getByRole("dialog").getByRole("heading",{name:"Grounded report",exact:true})).toBeVisible({timeout:60_000});
  await expect(page.getByText("COMPLETED",{exact:true}).first()).toBeVisible({timeout:60_000});
});
