/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Csrf */
        get: operations["csrf_api_auth_csrf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigations */
        get: operations["list_investigations_api_investigations_get"];
        put?: never;
        /** Create Investigation */
        post: operations["create_investigation_api_investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation */
        get: operations["get_investigation_api_investigations__investigation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/sources/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Investigation Url */
        post: operations["ingest_investigation_url_api_investigations__investigation_id__sources_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Investigation */
        post: operations["start_investigation_api_investigations__investigation_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Investigation */
        post: operations["cancel_investigation_api_investigations__investigation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research Tasks */
        get: operations["list_research_tasks_api_investigations__investigation_id__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation Progress */
        get: operations["get_investigation_progress_api_investigations__investigation_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigation Entities */
        get: operations["list_investigation_entities_api_investigations__investigation_id__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/entity-mentions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigation Entity Mentions */
        get: operations["list_investigation_entity_mentions_api_investigations__investigation_id__entity_mentions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/resolution-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigation Resolution Candidates */
        get: operations["list_investigation_resolution_candidates_api_investigations__investigation_id__resolution_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigation Relationships */
        get: operations["list_investigation_relationships_api_investigations__investigation_id__relationships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/relationship-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigation Relationship Candidates */
        get: operations["list_investigation_relationship_candidates_api_investigations__investigation_id__relationship_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigation Sources */
        get: operations["list_investigation_sources_api_investigations__investigation_id__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigation Documents */
        get: operations["list_investigation_documents_api_investigations__investigation_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/entities/{entity_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entity Evidence */
        get: operations["list_entity_evidence_api_investigations__investigation_id__entities__entity_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/relationships/{relationship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation Relationship */
        get: operations["get_investigation_relationship_api_investigations__investigation_id__relationships__relationship_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation Graph */
        get: operations["get_investigation_graph_api_investigations__investigation_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research-tasks/{research_task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Research Task */
        get: operations["get_research_task_api_research_tasks__research_task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research-tasks/{research_task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Research Task */
        post: operations["retry_research_task_api_research_tasks__research_task_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entity */
        get: operations["get_entity_api_entities__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships/{relationship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Relationship */
        get: operations["get_relationship_api_relationships__relationship_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships/{relationship_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Relationship Evidence */
        get: operations["list_relationship_evidence_api_relationships__relationship_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Investigation */
        post: operations["search_investigation_api_investigations__investigation_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Investigation */
        post: operations["ask_investigation_api_investigations__investigation_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{investigation_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_api_investigations__investigation_id__reports_get"];
        put?: never;
        /** Create Report */
        post: operations["create_report_api_investigations__investigation_id__reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_api_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entity-resolution-candidates/{candidate_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Entity Candidate */
        post: operations["accept_entity_candidate_api_entity_resolution_candidates__candidate_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entity-resolution-candidates/{candidate_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Entity Candidate */
        post: operations["reject_entity_candidate_api_entity_resolution_candidates__candidate_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationship-candidates/{candidate_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Relationship Candidate */
        post: operations["accept_relationship_candidate_api_relationship_candidates__candidate_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationship-candidates/{candidate_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Relationship Candidate */
        post: operations["reject_relationship_candidate_api_relationship_candidates__candidate_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /**
         * AssertionStatus
         * @enum {string}
         */
        AssertionStatus: "CONFIRMED" | "PROBABLE" | "POSSIBLE" | "UNVERIFIED" | "CONTRADICTED";
        /** CitationRead */
        CitationRead: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "EVIDENCE" | "CHUNK" | "DOCUMENT" | "SOURCE";
            /** Evidence Id */
            evidence_id?: string | null;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Document Id */
            document_id?: string | null;
            /** Source Id */
            source_id?: string | null;
            /** Start Offset */
            start_offset?: number | null;
            /** End Offset */
            end_offset?: number | null;
            /** Source Url */
            source_url?: string | null;
            /** Excerpt */
            excerpt?: string | null;
            /** Confidence */
            confidence?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** ComponentHealth */
        ComponentHealth: {
            status: components["schemas"]["ComponentStatus"];
            /** Detail */
            detail?: string | null;
        };
        /**
         * ComponentStatus
         * @enum {string}
         */
        ComponentStatus: "up" | "down";
        /** CsrfResponse */
        CsrfResponse: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** DocumentDetailRead */
        DocumentDetailRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            source: components["schemas"]["SourceSummaryRead"];
            /** Mime Type */
            mime_type: string;
            /** Content Hash */
            content_hash: string;
            /** Text Preview */
            text_preview: string;
            /** Content Length */
            content_length: number;
            /** Chunk Count */
            chunk_count: number;
            /** Mention Count */
            mention_count: number;
            /** Evidence Count */
            evidence_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Content Offset */
            content_offset: number;
            /** Content */
            content: string;
            /** Has More */
            has_more: boolean;
        };
        /** DocumentSummaryRead */
        DocumentSummaryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            source: components["schemas"]["SourceSummaryRead"];
            /** Mime Type */
            mime_type: string;
            /** Content Hash */
            content_hash: string;
            /** Text Preview */
            text_preview: string;
            /** Content Length */
            content_length: number;
            /** Chunk Count */
            chunk_count: number;
            /** Mention Count */
            mention_count: number;
            /** Evidence Count */
            evidence_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EntityAliasRead */
        EntityAliasRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Alias */
            alias: string;
            /** Normalized Alias */
            normalized_alias: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EntityMentionDetailRead */
        EntityMentionDetailRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Investigation Id
             * Format: uuid
             */
            investigation_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Entity Id */
            entity_id: string | null;
            entity_type: components["schemas"]["EntityType"];
            /** Surface Form */
            surface_form: string;
            /** Normalized Form */
            normalized_form: string;
            /** Start Offset */
            start_offset: number | null;
            /** End Offset */
            end_offset: number | null;
            /** Chunk Index */
            chunk_index: number | null;
            /** Extraction Method */
            extraction_method: string;
            /** Confidence */
            confidence: number;
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            source: components["schemas"]["SourceSummaryRead"];
            /** Document Title */
            document_title: string | null;
            /** Context Preview */
            context_preview: string;
        };
        /** EntityRead */
        EntityRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["EntityType"];
            /** Canonical Name */
            canonical_name: string;
            /** Normalized Name */
            normalized_name: string;
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Aliases */
            aliases: components["schemas"]["EntityAliasRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EntityResolutionCandidateDetailRead */
        EntityResolutionCandidateDetailRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Investigation Id
             * Format: uuid
             */
            investigation_id: string;
            /**
             * Mention Id
             * Format: uuid
             */
            mention_id: string;
            /**
             * Candidate Entity Id
             * Format: uuid
             */
            candidate_entity_id: string;
            /** Score */
            score: number;
            status: components["schemas"]["EntityResolutionCandidateStatus"];
            /** Signals */
            signals: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reviewed At */
            reviewed_at: string | null;
            mention: components["schemas"]["EntityMentionDetailRead"];
            provisional_entity: components["schemas"]["EntityRead"] | null;
            candidate_entity: components["schemas"]["EntityRead"];
        };
        /** EntityResolutionCandidateRead */
        EntityResolutionCandidateRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Investigation Id
             * Format: uuid
             */
            investigation_id: string;
            /**
             * Mention Id
             * Format: uuid
             */
            mention_id: string;
            /**
             * Candidate Entity Id
             * Format: uuid
             */
            candidate_entity_id: string;
            /** Score */
            score: number;
            status: components["schemas"]["EntityResolutionCandidateStatus"];
            /** Signals */
            signals: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reviewed At */
            reviewed_at: string | null;
        };
        /**
         * EntityResolutionCandidateStatus
         * @enum {string}
         */
        EntityResolutionCandidateStatus: "PENDING" | "ACCEPTED" | "REJECTED" | "AUTO_MATCHED";
        /**
         * EntityType
         * @enum {string}
         */
        EntityType: "PERSON" | "COMPANY" | "ORGANIZATION" | "DOMAIN" | "ADDRESS" | "DOCUMENT";
        /**
         * EvidenceType
         * @enum {string}
         */
        EvidenceType: "SUPPORTING" | "CONTRADICTING" | "TEMPORAL_UPDATE";
        /** GeneratedReportSection */
        GeneratedReportSection: {
            /** Heading */
            heading: string;
            /** Claims */
            claims?: components["schemas"]["GroundedClaim"][];
        };
        /** GraphEdgeRead */
        GraphEdgeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source
             * Format: uuid
             */
            source: string;
            /**
             * Target
             * Format: uuid
             */
            target: string;
            type: components["schemas"]["RelationshipType"];
            status: components["schemas"]["AssertionStatus"];
            /** Confidence */
            confidence: number;
            /** Evidence Count */
            evidence_count: number;
        };
        /** GraphNodeRead */
        GraphNodeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["EntityType"];
            /** Label */
            label: string;
            /** Mention Count */
            mention_count: number;
        };
        /** GroundedAnswerRead */
        GroundedAnswerRead: {
            /** Answer */
            answer: string;
            /** Abstained */
            abstained: boolean;
            /** Confidence */
            confidence: number;
            /** Claims */
            claims: components["schemas"]["GroundedClaim"][];
            /** Citations */
            citations: components["schemas"]["CitationRead"][];
            /** Limitations */
            limitations: string[];
            /** Contradictions */
            contradictions: {
                [key: string]: unknown;
            }[];
        };
        /** GroundedClaim */
        GroundedClaim: {
            /** Text */
            text: string;
            /** Citation Ids */
            citation_ids: string[];
            /** Confidence */
            confidence: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvestigationCountsRead */
        InvestigationCountsRead: {
            /** Tasks */
            tasks: number;
            /** Entities */
            entities: number;
            /** Relationships */
            relationships: number;
            /** Contradictions */
            contradictions: number;
            /** Sources */
            sources: number;
            /** Documents */
            documents: number;
        };
        /** InvestigationCreate */
        InvestigationCreate: {
            /** Title */
            title: string;
            /** Original Query */
            original_query: string;
        };
        /** InvestigationEntityRead */
        InvestigationEntityRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["EntityType"];
            /** Canonical Name */
            canonical_name: string;
            /** Normalized Name */
            normalized_name: string;
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Aliases */
            aliases: components["schemas"]["EntityAliasRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Mention Count */
            mention_count: number;
        };
        /** InvestigationGraphRead */
        InvestigationGraphRead: {
            /** Nodes */
            nodes: components["schemas"]["GraphNodeRead"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeRead"][];
            /** Truncated */
            truncated: boolean;
            /** Total Nodes */
            total_nodes: number;
        };
        /** InvestigationProgressRead */
        InvestigationProgressRead: {
            /** Total */
            total: number;
            /** Pending */
            pending: number;
            /** Running */
            running: number;
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Cancelled */
            cancelled: number;
            /** Percent */
            percent: number;
        };
        /** InvestigationRead */
        InvestigationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Original Query */
            original_query: string;
            status: components["schemas"]["InvestigationStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** InvestigationReportRead */
        InvestigationReportRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Investigation Id
             * Format: uuid
             */
            investigation_id: string;
            /** Subject Entity Id */
            subject_entity_id: string | null;
            type: components["schemas"]["InvestigationReportType"];
            status: components["schemas"]["InvestigationReportStatus"];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Input Fingerprint */
            input_fingerprint: string;
            /** Attempts */
            attempts: number;
            /** Last Error Code */
            last_error_code: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            content: components["schemas"]["ReportContentRead"] | null;
            /** Last Error Message */
            last_error_message: string | null;
        };
        /**
         * InvestigationReportStatus
         * @enum {string}
         */
        InvestigationReportStatus: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED";
        /** InvestigationReportSummaryRead */
        InvestigationReportSummaryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Investigation Id
             * Format: uuid
             */
            investigation_id: string;
            /** Subject Entity Id */
            subject_entity_id: string | null;
            type: components["schemas"]["InvestigationReportType"];
            status: components["schemas"]["InvestigationReportStatus"];
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Input Fingerprint */
            input_fingerprint: string;
            /** Attempts */
            attempts: number;
            /** Last Error Code */
            last_error_code: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * InvestigationReportType
         * @enum {string}
         */
        InvestigationReportType: "EXECUTIVE_SUMMARY" | "CORPORATE_PROFILE" | "RELATIONSHIP_SUMMARY" | "TIMELINE_SUMMARY";
        /**
         * InvestigationStatus
         * @enum {string}
         */
        InvestigationStatus: "DRAFT" | "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED" | "PARTIAL";
        /** InvestigationSummaryRead */
        InvestigationSummaryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Original Query */
            original_query: string;
            status: components["schemas"]["InvestigationStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            progress: components["schemas"]["InvestigationProgressRead"];
            counts: components["schemas"]["InvestigationCountsRead"];
        };
        JsonValue: unknown;
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @default tracelink-api
             * @constant
             */
            service: "tracelink-api";
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ReadinessChecks */
        ReadinessChecks: {
            database: components["schemas"]["ComponentHealth"];
            redis: components["schemas"]["ComponentHealth"];
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            checks: components["schemas"]["ReadinessChecks"];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** RelationshipCandidateRead */
        RelationshipCandidateRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Investigation Id
             * Format: uuid
             */
            investigation_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            source_entity: components["schemas"]["RelationshipEntitySummary"];
            target_entity: components["schemas"]["RelationshipEntitySummary"];
            type: components["schemas"]["RelationshipType"];
            claim_kind: components["schemas"]["RelationshipClaimKind"];
            /** Confidence */
            confidence: number;
            /** Score */
            score: number;
            status: components["schemas"]["RelationshipCandidateStatus"];
            /** Extraction Method */
            extraction_method: string;
            /** Signals */
            signals: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Temporal Start */
            temporal_start: string | null;
            /** Temporal End */
            temporal_end: string | null;
            /** Evidence Preview */
            evidence_preview: string | null;
            /** Reason Codes */
            reason_codes?: string[];
            source?: components["schemas"]["SourceSummaryRead"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Reviewed At */
            reviewed_at?: string | null;
        };
        /**
         * RelationshipCandidateStatus
         * @enum {string}
         */
        RelationshipCandidateStatus: "PENDING" | "ACCEPTED" | "REJECTED" | "AUTO_ACCEPTED" | "CONTRADICTED";
        /**
         * RelationshipClaimKind
         * @enum {string}
         */
        RelationshipClaimKind: "AFFIRMS" | "NEGATES" | "ENDS";
        /** RelationshipDetailRead */
        RelationshipDetailRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            source_entity: components["schemas"]["RelationshipEntitySummary"];
            target_entity: components["schemas"]["RelationshipEntitySummary"];
            type: components["schemas"]["RelationshipType"];
            /** Confidence */
            confidence: number;
            status: components["schemas"]["AssertionStatus"];
            /** First Observed At */
            first_observed_at: string | null;
            /** Last Observed At */
            last_observed_at: string | null;
            /** Temporal Start */
            temporal_start: string | null;
            /** Temporal End */
            temporal_end: string | null;
            /** Evidence Count */
            evidence_count: number;
            /** Claims */
            claims: components["schemas"]["RelationshipCandidateRead"][];
            /** Evidence */
            evidence: components["schemas"]["RelationshipEvidenceRead"][];
        };
        /** RelationshipEntitySummary */
        RelationshipEntitySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["EntityType"];
            /** Canonical Name */
            canonical_name: string;
        };
        /** RelationshipEvidenceRead */
        RelationshipEvidenceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Investigation Id
             * Format: uuid
             */
            investigation_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Document Id */
            document_id: string | null;
            /** Relationship Id */
            relationship_id: string | null;
            evidence_type: components["schemas"]["EvidenceType"];
            /** Confidence */
            confidence: number;
            /** Start Offset */
            start_offset: number | null;
            /** End Offset */
            end_offset: number | null;
            /** Locator */
            locator: string | null;
            /** Preview */
            preview: string | null;
            source?: components["schemas"]["SourceSummaryRead"] | null;
            /** Document Title */
            document_title?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RelationshipRead */
        RelationshipRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            source_entity: components["schemas"]["RelationshipEntitySummary"];
            target_entity: components["schemas"]["RelationshipEntitySummary"];
            type: components["schemas"]["RelationshipType"];
            /** Confidence */
            confidence: number;
            status: components["schemas"]["AssertionStatus"];
            /** First Observed At */
            first_observed_at: string | null;
            /** Last Observed At */
            last_observed_at: string | null;
            /** Temporal Start */
            temporal_start: string | null;
            /** Temporal End */
            temporal_end: string | null;
            /** Evidence Count */
            evidence_count: number;
        };
        /**
         * RelationshipType
         * @enum {string}
         */
        RelationshipType: "DIRECTOR_OF" | "OWNER_OF" | "EMPLOYEE_OF" | "RELATED_TO" | "SHARES_ADDRESS_WITH" | "OWNS_DOMAIN" | "MENTIONED_IN" | "SUBSIDIARY_OF" | "PARTNER_OF";
        /** ReportContentRead */
        ReportContentRead: {
            /** Title */
            title: string;
            /** Abstained */
            abstained: boolean;
            /** Executive Summary */
            executive_summary: string;
            /** Summary Claims */
            summary_claims?: components["schemas"]["GroundedClaim"][];
            /** Sections */
            sections: components["schemas"]["GeneratedReportSection"][];
            /** Key Entities */
            key_entities: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Key Relationships */
            key_relationships: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Timeline */
            timeline: components["schemas"]["ReportTimelineItemRead"][];
            /** Contradictions */
            contradictions: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Limitations */
            limitations: string[];
            /** Citations */
            citations: components["schemas"]["CitationRead"][];
        };
        /** ReportCreate */
        ReportCreate: {
            type: components["schemas"]["InvestigationReportType"];
            /** Subject Entity Id */
            subject_entity_id?: string | null;
        };
        /** ReportTimelineItemRead */
        ReportTimelineItemRead: {
            /** Date */
            date: string;
            /** Kind */
            kind: string;
        };
        /** ResearchTaskRead */
        ResearchTaskRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Investigation Id
             * Format: uuid
             */
            investigation_id: string;
            type: components["schemas"]["ResearchTaskType"];
            status: components["schemas"]["ResearchTaskStatus"];
            /** Query */
            query: string;
            /** Source Type */
            source_type: string | null;
            /** Attempts */
            attempts: number;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Last Error Code */
            last_error_code: string | null;
            /** Last Error Message */
            last_error_message: string | null;
            /** Active Celery Task Id */
            active_celery_task_id: string | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ResearchTaskResult */
        ResearchTaskResult: {
            /** Connector */
            connector: string;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "skipped" | "failed";
            /** Source Ids */
            source_ids?: string[];
            /** Document Ids */
            document_ids?: string[];
            /**
             * Result Count
             * @default 0
             */
            result_count: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * ResearchTaskStatus
         * @enum {string}
         */
        ResearchTaskStatus: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELLED";
        /**
         * ResearchTaskType
         * @enum {string}
         */
        ResearchTaskType: "IDENTIFY_ENTITY" | "WEB_SEARCH" | "DOMAIN_LOOKUP" | "PUBLIC_MENTIONS";
        /** RetrievalFilterInput */
        RetrievalFilterInput: {
            /** Source Ids */
            source_ids?: string[];
            /** Document Ids */
            document_ids?: string[];
            /** Entity Ids */
            entity_ids?: string[];
            /** Relationship Types */
            relationship_types?: components["schemas"]["RelationshipType"][];
            /** Published From */
            published_from?: string | null;
            /** Published To */
            published_to?: string | null;
        };
        /** SearchHitRead */
        SearchHitRead: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Chunk Index */
            chunk_index: number;
            /** Chunk Text */
            chunk_text: string;
            /** Start Offset */
            start_offset: number;
            /** End Offset */
            end_offset: number;
            /** Source Url */
            source_url: string;
            /** Source Title */
            source_title: string | null;
            /** Published At */
            published_at: string | null;
            /** Semantic Score */
            semantic_score: number;
            /** Lexical Score */
            lexical_score: number;
            /** Evidence Boost */
            evidence_boost: number;
            /** Combined Score */
            combined_score: number;
            /** Matched Entity Ids */
            matched_entity_ids: string[];
            /** Matched Relationship Types */
            matched_relationship_types: string[];
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /** Top K */
            top_k?: number | null;
            filters?: components["schemas"]["RetrievalFilterInput"];
        };
        /** SourceSummaryRead */
        SourceSummaryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Publisher */
            publisher: string | null;
            /** Url */
            url: string;
            /** Title */
            title: string | null;
            /** Published At */
            published_at: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Document Count
             * @default 0
             */
            document_count: number;
        };
        /** UrlIngestionCreate */
        UrlIngestionCreate: {
            /** Url */
            url: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Last Login At */
            last_login_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    csrf_api_auth_csrf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracelink_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracelink_access?: string | null;
                tracelink_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigations_api_investigations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationSummaryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investigation_api_investigations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_api_investigations__investigation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationSummaryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_investigation_url_api_investigations__investigation_id__sources_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UrlIngestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchTaskResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_investigation_api_investigations__investigation_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_investigation_api_investigations__investigation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_research_tasks_api_investigations__investigation_id__tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchTaskRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_progress_api_investigations__investigation_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationProgressRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigation_entities_api_investigations__investigation_id__entities_get: {
        parameters: {
            query?: {
                entity_type?: components["schemas"]["EntityType"] | null;
                q?: string | null;
                sort?: "recent" | "mention_count";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationEntityRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigation_entity_mentions_api_investigations__investigation_id__entity_mentions_get: {
        parameters: {
            query?: {
                entity_id?: string | null;
                document_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityMentionDetailRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigation_resolution_candidates_api_investigations__investigation_id__resolution_candidates_get: {
        parameters: {
            query?: {
                candidate_status?: components["schemas"]["EntityResolutionCandidateStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResolutionCandidateDetailRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigation_relationships_api_investigations__investigation_id__relationships_get: {
        parameters: {
            query?: {
                relationship_type?: components["schemas"]["RelationshipType"] | null;
                relationship_status?: components["schemas"]["AssertionStatus"] | null;
                entity_id?: string | null;
                sort?: "recent" | "evidence_count" | "confidence";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigation_relationship_candidates_api_investigations__investigation_id__relationship_candidates_get: {
        parameters: {
            query?: {
                candidate_status?: components["schemas"]["RelationshipCandidateStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipCandidateRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigation_sources_api_investigations__investigation_id__sources_get: {
        parameters: {
            query?: {
                q?: string | null;
                source_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSummaryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigation_documents_api_investigations__investigation_id__documents_get: {
        parameters: {
            query?: {
                q?: string | null;
                mime_type?: string | null;
                source_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummaryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entity_evidence_api_investigations__investigation_id__entities__entity_id__evidence_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
                entity_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipEvidenceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_relationship_api_investigations__investigation_id__relationships__relationship_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
                relationship_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_graph_api_investigations__investigation_id__graph_get: {
        parameters: {
            query?: {
                entity_type?: components["schemas"]["EntityType"] | null;
                relationship_type?: components["schemas"]["RelationshipType"] | null;
                relationship_status?: components["schemas"]["AssertionStatus"] | null;
                q?: string | null;
                focus_entity_id?: string | null;
                max_nodes?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationGraphRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_research_task_api_research_tasks__research_task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_task_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchTaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_research_task_api_research_tasks__research_task_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                research_task_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchTaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_api_entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_relationship_api_relationships__relationship_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relationship_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_relationship_evidence_api_relationships__relationship_id__evidence_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                relationship_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipEvidenceRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_investigation_api_investigations__investigation_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHitRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_investigation_api_investigations__investigation_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundedAnswerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_investigations__investigation_id__reports_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationReportSummaryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_investigations__investigation_id__reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationReportSummaryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSummaryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_documents__document_id__get: {
        parameters: {
            query?: {
                content_offset?: number;
                content_limit?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipEvidenceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_entity_candidate_api_entity_resolution_candidates__candidate_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResolutionCandidateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_entity_candidate_api_entity_resolution_candidates__candidate_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResolutionCandidateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_relationship_candidate_api_relationship_candidates__candidate_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipCandidateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_relationship_candidate_api_relationship_candidates__candidate_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: {
                tracelink_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipCandidateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
